---
- name: install docker
  include_role: 
    name: install_docker

- name: install python and etc
  become: yes
  yum:
    name: 
    - python3
    - python-docker-py
    state: latest

- name: log into docker hub
  docker_login:
    email: "{{ dockerhub_email }}"
    username: "{{ dockerhub_login }}"
    password: "{{ dockerhub_password }}"
    state: present
    
- name: start docker container from docker hub
  docker_container:
    name: flask
    state: started
    image: anmean/student-exam2:flask
    ports:
      - "5000:5000"
    detach: true
