---
- name: install docker
  include_role: 
    name: install_docker

- name: log into docker hub
  docker_login:
    email: "{{ dockerhub_email }}"
    username: "{{ dockerhub_login }}"
    password: "{{ dockerhub_password }}"
    
- name: install ansible galaxy module docker_network
  community.general.ansible_galaxy_install:
    type: collection
    name: community.docker

- name: set docker network for web app
  community.docker.docker_network:
    name: network_web

- name: start docker container from docker hub
  docker_container:
    name: flask
    state: started
    image: anmean/student-exam2:flask
    ports:
      - "5000:5000"
    networks:
      - name: network_web
    detach: true
