---
- name: install docker
  include_role: 
    name: install_docker

- name: log into docker hub
  docker_login:
    email: "{{ dockerhub_email }}"
    username: "{{ dockerhub_login }}"
    password: "{{ dockerhub_password }}"

- name: set docker network for web app
    community.docker.docker_network:
      name: network_web

- name: start docker container from docker hub
  docker_container:
    name: flask
    state: started
    image: anmean/student-exam2:flask
    ports:
      - "5000:5000"
    networks:
      - name: network_web
    detach: true
